routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layout', ['content' => view('home')]);
});

Route::get('export', \App\Http\Controllers\ExportController::class);

app/Models/PlayerStats.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Spatie\QueryBuilder\AllowedFilter;
use Spatie\QueryBuilder\QueryBuilder;

class PlayerStats extends Model
{
    protected $table = 'player_totals';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [];


}

app/Models/Roster.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Spatie\QueryBuilder\AllowedFilter;
use Spatie\QueryBuilder\QueryBuilder;

class Roster extends Model
{
    protected $table = 'roster';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [];

    public function getCollection(Request $request)
    {
        $query =  QueryBuilder::for(Roster::class, new Request([
            'filter' => $request->only([
                'search', 'team', 'player', 'position'
            ]),
        ]))->allowedFilters(
                AllowedFilter::scope('team', 'byTeam'),
                AllowedFilter::scope('player', 'byPlayer'),
                AllowedFilter::scope('position', 'byPosition')
        )->join('player_totals', 'player_id', '=', 'id');


        return $query->get();
    }

    public function scopeByTeam(Builder $query, $team)
    {
        $query->where('team_code', '=', $team);
    }

    public function scopeByPlayer(Builder $query, $player)
    {
        $query->where('name', 'like', '%'.$player.'%');
    }

    public function scopeByPosition(Builder $query, $position)
    {
        $query->where('pos', '=', $position);
    }

    public function stats()
    {
        return $this->hasOne(PlayerStats::class, 'player_id', 'id');
    }

    public function getTotalPointsAttribute()
    {
        return ($this->field_goals * 2) + $this['3pt'] + $this->free_throws;
    }

    public function getTotalReboundsAttribute()
    {
        return $this->offensive_rebounds + $this->defensive_rebounds;
    }

    public function getFgPctAttribute()
    {
        if (!$this['field_goals_attempted']) {
            return 0.00;
        }
        $pct =  100 * $this['field_goals'] / $this['field_goals_attempted'];
        return number_format($pct, 2);
    }

    public function getThreePctAttribute()
    {
        if (!$this['three_pt_attempted']) {
            return 0.00;
        }
        $pct =  100 * $this['three_pt'] / $this['three_pt_attempted'];
        return number_format($pct, 2);
    }

    public function getFtPctAttribute()
    {
        if (!$this['free_throws_attempted']) {
            return 0.00;
        }
        $pct =  100 * $this['free_throws'] / $this['free_throws_attempted'];
        return number_format($pct, 2);
    }

    public function getTwoPctAttribute()
    {
        if (!$this['two_pt_attempted']) {
            return 0.00;
        }
        $pct =  100 * $this['two_pt'] / $this['two_pt_attempted'];
        return number_format($pct, 2);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ExportController.php
<?php

namespace App\Http\Controllers;

use App\Interfaces\ExportData\ExportData;
use App\Interfaces\ExportFormat\ExportFormat;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller as BaseController;

class ExportController extends BaseController
{
    /**
     * Single method class
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function __invoke(Request $request)
    {
        $exportData = new ExportData($request->type);
        if (!$data =  $exportData->getData($request)) {
            return $exportData->getError();
        }

        return (new ExportFormat($data, $request->input('format')))->getFormattedData();
    }
}

resources/views/home.blade.php
<div class="grid place-items-center h-screen ">
    <div class="bg-blue-100 p-12 flex justify-between w-1/5">
        <div class="text">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                <a href="/export">Export</a>
            </button>
        </div>
        <div>
            <button class="bg-red-400 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                <a href="/report">Report</a>
            </button>
        </div>
    </div>
</div>

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>NBA Stats</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">

    <!-- Styles -->
    <style>

    </style>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body {
            font-family: 'Nunito', sans-serif;
        }
    </style>
</head>
<body class="antialiased">
<?php echo $content ?>

</body>
</html>

resources/views/players.blade.php
<div class="p-12 flex justify-between w-4/5">
    <table class="table-auto w-4/5">
        <thead>
        <tr>
            <th>Team Code</th>
            <th>Number</th>
            <th>Name</th>
            <th>Position</th>
            <th>Height</th>
            <th>Weight</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($players as $player) { ?>
        <tr>
            <td><?php echo $player->team_code ?></td>
            <td><?php echo $player->number ?></td>
            <td><?php echo $player->name ?></td>
            <td><?php echo $player->pos ?></td>
            <td><?php echo $player->height ?></td>
            <td><?php echo $player->weight ?></td>
        </tr>
        <?php } ?>

        </tbody>
    </table>
</div>

resources/views/playerstats.blade.php
<div class="p-12 flex justify-between">
    <table>
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Games</th>
            <th>Games Started</th>
            <th>Minutes Played</th>
            <th>Field Goals</th>
            <th>Field Goals Attempted</th>
            <th>3pt</th>
            <th>3pt Attempted</th>
            <th>2pt</th>
            <th>2pt Attempted</th>
            <th>Free Throws</th>
            <th>Free Throws Attempted</th>
            <th>Offensive Rebounds</th>
            <th>Defensive Rebounds</th>
            <th>Assists</th>
            <th>Steals</th>
            <th>Blocks</th>
            <th>Turnovers</th>
            <th>Personal Fouls</th>
            <th>Total Points</th>
            <th>Field Goals Pct</th>
            <th>3pt Pct</th>
            <th>2pt Pct</th>
            <th>Free Throws Pct</th>
            <th>Total Rebounds</th>
        </tr>
        <?php foreach ($players as $player) { ?>
        <tr>
            <td><?php echo $player->name ?></td>
            <td><?php echo $player->age ?></td>
            <td><?php echo $player->games ?></td>
            <td><?php echo $player->games_started ?></td>
            <td><?php echo $player->minutes_played ?></td>
            <td><?php echo $player->field_goals ?></td>
            <td><?php echo $player->field_goals_attempted ?></td>
            <td><?php echo $player['three_pt'] ?></td>
            <td><?php echo $player['three_pt_attempted'] ?></td>
            <td><?php echo $player['two_pt'] ?></td>
            <td><?php echo $player['two_pt_attempted'] ?></td>
            <td><?php echo $player->free_throws ?></td>
            <td><?php echo $player->free_throws_attempted ?></td>
            <td><?php echo $player->offensive_rebounds ?></td>
            <td><?php echo $player->defensive_rebounds ?></td>
            <td><?php echo $player->assists ?></td>
            <td><?php echo $player->steals ?></td>
            <td><?php echo $player->blocks ?></td>
            <td><?php echo $player->turnovers ?></td>
            <td><?php echo $player->personal_fouls ?></td>
            <td><?php echo $player->total_points ?></td>
            <td><?php echo $player->fg_pct ?></td>
            <td><?php echo $player->three_pct ?></td>
            <td><?php echo $player->two_pct ?></td>
            <td><?php echo $player->ft_pct ?></td>
            <td><?php echo $player->total_rebounds ?></td>
        </tr>
        <?php } ?>
    </table>
</div>